spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hidden-method:
      filter:
        enabled: true #springboot 2.2.x 高版本中此处开启才能正常接受到文件
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  cache:
    # 缓存类型
    type: REDIS
  messages:
    basename: i18n/messages

springdoc:
  default-flat-param-object: true

server:
  shutdown: graceful
  max-http-request-header-size: 10240000
  tomcat:
    uri-encoding: UTF-8

knife4j:
  enable: true
  documents:
    - group: default
      name: 接口说明
      locations: classpath:markdown/*
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-version: true
    enable-open-api: false
    enable-footer: false
    enable-after-script: false
    enable-dynamic-parameter: true

logging:
  file:
    path: ./logs/${spring.application.name}
  level:
    root: info

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteTime
      logic-delete-value: REPLACE(unix_timestamp(current_timestamp(3)),'.','')
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: ${spring.application.name}-satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否在初始化配置时打印版本字符画
  is-print: false
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # 是否尝试从请求体里读取token
  is-read-body: false
